# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ sveltekit_tailwindcss_frontend ]
  pull_request:
    branches: [ sveltekit_tailwindcss_frontend ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  E2E-tests:
    name: End-to-End tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        spec:
          - cypress/integration/**
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'zulu'
          architecture: x64
      - name: Build backend
        run: ./gradlew bootrun
      - name: Build frontend
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm run frontend:build
      - name: Cypress Test
        run: npm run cy:run
